force-app/main/default/objects/ID_Number_Reference_Count__c/ID_Number_Reference_Count__c.object-meta.xml
<CustomObject>
    <description>Stores decoded SA ID Number information, as well as a count of how many times it has been requested.</description>
    <label>ID Number Reference Count</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Number Reference Counts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ID_Number_Reference_Count__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ID_Number_Reference_Count__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ID_Number_Reference_Count__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>ID Number</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ID_Number_Reference_Count__c/fields/NumReferences__c.field-meta.xml
<CustomField>
    <fullName>NumReferences__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NumReferences</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ID_Number_Reference_Count__c/fields/SA_Citizen__c.field-meta.xml
<CustomField>
    <fullName>SA_Citizen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SA Citizen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IDNumberUtils.cls
public class IDNumberUtils {

    public static void AddIDNumber (String IDNumber, String birthdate, String gender, Boolean citizen) {
        ID_Number_Reference_Count__c[] recs = [
            select ID_Number__c, Date_of_Birth__c, Gender__c, SA_Citizen__c, NumReferences__c
            from ID_Number_Reference_Count__c
            where ID_Number__c = :IDNumber
            ];
        
        if (recs.isEmpty()) {
            String[] dateParts = birthdate.split('-');
            Date DoB = Date.newInstance (Integer.valueOf(dateParts[0]), Integer.valueOf(dateParts[1]), Integer.valueOf(dateParts[2]));
            ID_Number_Reference_Count__c NewRec = new ID_Number_Reference_Count__c (
                ID_Number__c = IDNumber, Date_of_Birth__c = DoB, Gender__c = gender, SA_Citizen__c = citizen, NumReferences__c = 1
            );
            insert NewRec;
        } else {
            recs[0].NumReferences__c = recs[0].NumReferences__c+1;
            update recs;
        }
    }
}